/**
 * FFHub 各 action 的入参/出参 Zod schema 与语义标注。
 *
 * **由 `scripts/migrate` 从 open-connector 的 action 定义生成**,生成后归本仓库所有:
 * 可以直接改(收紧 schema、改 description、修 effect)。改过的 action 请登记进同目录的
 * `handwritten.json`,否则重新生成会覆盖你的修改,等价闸门也会拿上游 schema 判它。
 *
 * `effect` 上游没有这个轴,生成时按 action 名前缀**播种**(读前缀 read、删除前缀
 * destructive、其余 write),保守取值,以人工校正为准。
 */

import { z } from 'zod/v4'

export const createFfmpegTaskInput = z.strictObject({
  command: z.string().min(1).describe('Full FFmpeg command or argument-only command string accepted by FFHub, including remote input URLs and output file names.'),
  webhook: z.url().describe('Optional callback URL that receives the same payload as get_ffmpeg_task.').optional(),
  withMetadata: z.boolean().describe('Whether FFHub should collect ffprobe metadata for generated output files.').optional(),
}).describe('Input parameters for creating an FFHub FFmpeg task.')

export const createFfmpegTaskOutput = z.strictObject({
  taskId: z.string().describe('Created FFHub task ID.'),
}).describe('Identifier for the created FFHub task.')

export const getFfmpegTaskInput = z.strictObject({
  taskId: z.string().min(1).describe('FFHub task ID to retrieve.'),
}).describe('Identifier of the FFHub task to retrieve.')

export const getFfmpegTaskOutput = z.strictObject({
  task: z.strictObject({
    taskId: z.string().describe('FFHub task ID.'),
    userId: z.string().describe('FFHub customer identifier when returned.').nullable(),
    status: z.enum(['pending', 'running', 'completed', 'failed']).describe('FFHub task status.'),
    progress: z.int().describe('Task progress percentage when returned.').nullable(),
    error: z.string().describe('Task error message when the task failed.').nullable(),
    elapsed: z.string().describe('Worker execution time in seconds when returned.').nullable(),
    totalElapsed: z.string().describe('Total elapsed time from creation to completion in seconds when returned.').nullable(),
    createdAt: z.string().describe('Task creation timestamp.').nullable(),
    finishedAt: z.string().describe('Task completion timestamp, or null when pending.').nullable(),
    outputs: z.array(z.strictObject({
      filename: z.string().describe('Output file name.'),
      url: z.string().describe('Output file URL.'),
      size: z.int().describe('Output file size in bytes when available.').nullable(),
      metadata: z.record(z.string(), z.unknown().describe('One raw ffprobe metadata value returned by FFHub.')).describe('Raw ffprobe metadata object returned by FFHub when requested.').nullable(),
    }).describe('Single FFHub output file.')).describe('Output files generated by the task.'),
  }).describe('Normalized FFHub task.'),
}).describe('Single FFHub task detail.')

export const listFfmpegTasksInput = z.strictObject({
  userId: z.string().min(1).describe('Optional FFHub customer identifier.').optional(),
  status: z.enum(['pending', 'running', 'completed', 'failed']).describe('FFHub task status.').optional(),
  limit: z.int().min(1).max(100).describe('Maximum number of tasks to return, from 1 to 100.').optional(),
  offset: z.int().min(0).describe('Number of tasks to skip before reading the current page.').optional(),
}).describe('Filters for listing FFHub FFmpeg tasks.')

export const listFfmpegTasksOutput = z.strictObject({
  tasks: z.array(z.strictObject({
    taskId: z.string().describe('FFHub task ID.'),
    userId: z.string().describe('FFHub customer identifier when returned.').nullable(),
    status: z.enum(['pending', 'running', 'completed', 'failed']).describe('FFHub task status.'),
    progress: z.int().describe('Task progress percentage when returned.').nullable(),
    error: z.string().describe('Task error message when the task failed.').nullable(),
    elapsed: z.string().describe('Worker execution time in seconds when returned.').nullable(),
    totalElapsed: z.string().describe('Total elapsed time from creation to completion in seconds when returned.').nullable(),
    createdAt: z.string().describe('Task creation timestamp.').nullable(),
    finishedAt: z.string().describe('Task completion timestamp, or null when pending.').nullable(),
    outputs: z.array(z.strictObject({
      filename: z.string().describe('Output file name.'),
      url: z.string().describe('Output file URL.'),
      size: z.int().describe('Output file size in bytes when available.').nullable(),
      metadata: z.record(z.string(), z.unknown().describe('One raw ffprobe metadata value returned by FFHub.')).describe('Raw ffprobe metadata object returned by FFHub when requested.').nullable(),
    }).describe('Single FFHub output file.')).describe('Output files generated by the task.'),
  }).describe('Normalized FFHub task.')).describe('Normalized FFHub tasks.'),
  total: z.int().min(0).describe('Total number of matching FFHub tasks.'),
}).describe('Paginated FFHub task list.')

/** action 名 → 注册用的 OperationSpec(description / effect / schema)。 */
export const ffhubActions = {
  create_ffmpeg_task: {
    description: 'Create a new FFHub FFmpeg transcoding task from a full FFmpeg command or argument-only command string.',
    effect: 'write',
    inputSchema: createFfmpegTaskInput,
    outputSchema: z.toJSONSchema(createFfmpegTaskOutput, { io: 'output', unrepresentable: 'any' }),
  },
  get_ffmpeg_task: {
    description: 'Get the current status, timing, error, and output files for one FFHub FFmpeg task.',
    effect: 'read',
    inputSchema: getFfmpegTaskInput,
    outputSchema: z.toJSONSchema(getFfmpegTaskOutput, { io: 'output', unrepresentable: 'any' }),
  },
  list_ffmpeg_tasks: {
    description: 'List FFHub FFmpeg tasks with optional customer, status, limit, and offset filters.',
    effect: 'read',
    inputSchema: listFfmpegTasksInput,
    outputSchema: z.toJSONSchema(listFfmpegTasksOutput, { io: 'output', unrepresentable: 'any' }),
  },
} as const
