/**
 * Clerk 各 action 的入参/出参 Zod schema 与语义标注。
 *
 * **由 `scripts/migrate` 从 open-connector 的 action 定义生成**,生成后归本仓库所有:
 * 可以直接改(收紧 schema、改 description、修 effect)。改过的 action 请登记进同目录的
 * `handwritten.json`,否则重新生成会覆盖你的修改,等价闸门也会拿上游 schema 判它。
 *
 * `effect` 上游没有这个轴,生成时按 action 名前缀**播种**(读前缀 read、删除前缀
 * destructive、其余 write),保守取值,以人工校正为准。
 */

import { z } from 'zod/v4'

export const listUsersInput = z.strictObject({
  email_address: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  phone_number: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  username: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  user_id: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  external_id: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  query: z.string().min(1).describe('A search query for Clerk users.').optional(),
  order_by: z.string().min(1).describe('The Clerk order field, such as -created_at.').optional(),
  limit: z.int().min(1).max(500).describe('Maximum number of users to return.').optional(),
  offset: z.int().min(0).describe('Number of users to skip before returning results.').optional(),
}).describe('Input for listing Clerk users.')

export const listUsersOutput = z.strictObject({
  users: z.array(z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.')).describe('Clerk users returned by the list request.'),
  total_count: z.int().describe('Total number of matching users reported by Clerk.'),
}).describe('Output returned after listing Clerk users.')

export const countUsersInput = z.strictObject({
  email_address: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  phone_number: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  username: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  user_id: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  external_id: z.array(z.string().min(1).describe('A string filter value.')).describe('A list of string values used by Clerk filters.').optional(),
  query: z.string().min(1).describe('A search query for Clerk users.').optional(),
}).describe('Input for counting Clerk users.')

export const countUsersOutput = z.strictObject({
  total_count: z.int().describe('Total number of matching users reported by Clerk.'),
}).describe('Output returned after counting Clerk users.')

export const getUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
}).describe('Input for a Clerk user ID.')

export const getUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const createUserInput = z.strictObject({
  email_address: z.array(z.email().describe('An email address attached to the Clerk user.')).describe('Email addresses to add to the new user.').optional(),
  phone_number: z.array(z.string().min(1).describe('A phone number attached to the Clerk user.')).describe('Phone numbers to add to the new user.').optional(),
  web3_wallet: z.array(z.string().min(1).describe('A Web3 wallet address.')).describe('Web3 wallet addresses to add to the new user.').optional(),
  external_id: z.string().min(1).describe('An external ID for the user.').optional(),
  first_name: z.string().min(1).describe('The user\'s first name.').optional(),
  last_name: z.string().min(1).describe('The user\'s last name.').optional(),
  username: z.string().min(1).describe('The username attached to the Clerk user.').optional(),
  password: z.string().min(1).describe('The user\'s password.').optional(),
  password_digest: z.string().min(1).describe('A password digest for the user.').optional(),
  password_hasher: z.string().min(1).describe('The hashing algorithm used for password_digest.').optional(),
  skip_password_checks: z.boolean().describe('Whether Clerk should skip password validation checks.').optional(),
  skip_password_requirement: z.boolean().describe('Whether Clerk should allow creating the user without a password.').optional(),
  totp_secret: z.string().min(1).describe('The TOTP secret to add to the user.').optional(),
  backup_codes: z.array(z.string().min(1).describe('A backup code.')).describe('Backup codes to add to the user.').optional(),
  public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  created_at: z.string().min(1).describe('The RFC3339 datetime to set as the user\'s creation time.').optional(),
}).describe('Input for creating a Clerk user.')

export const createUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const updateUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
  first_name: z.string().min(1).describe('The user\'s first name.').optional(),
  last_name: z.string().min(1).describe('The user\'s last name.').optional(),
  primary_email_address_id: z.string().min(1).describe('The primary email address ID.').optional(),
  primary_phone_number_id: z.string().min(1).describe('The primary phone number ID.').optional(),
  primary_web3_wallet_id: z.string().min(1).describe('The primary Web3 wallet ID.').optional(),
  username: z.string().min(1).describe('The username attached to the Clerk user.').optional(),
  password: z.string().min(1).describe('The user\'s password.').optional(),
  password_digest: z.string().min(1).describe('A password digest for the user.').optional(),
  password_hasher: z.string().min(1).describe('The hashing algorithm used for password_digest.').optional(),
  skip_password_checks: z.boolean().describe('Whether Clerk should skip password validation checks.').optional(),
  skip_password_requirement: z.boolean().describe('Whether Clerk should allow the user without a password.').optional(),
  sign_out_of_other_sessions: z.boolean().describe('Whether Clerk should sign the user out of other sessions.').optional(),
  totp_secret: z.string().min(1).describe('The TOTP secret to add to the user.').optional(),
  backup_codes: z.array(z.string().min(1).describe('A backup code.')).describe('Backup codes to add to the user.').optional(),
  public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
}).describe('Input for updating a Clerk user.')

export const updateUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const updateUserMetadataInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
  public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
  unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
}).describe('Input for updating Clerk user metadata.')

export const updateUserMetadataOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const deleteUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
}).describe('Input for a Clerk user ID.')

export const deleteUserOutput = z.strictObject({
  deleted_object: z.strictObject({
    id: z.string().describe('The deleted object ID.'),
    object: z.string().describe('The deleted object type.').optional(),
    deleted: z.boolean().describe('Whether the object was deleted.'),
  }).describe('A Clerk deleted object response.'),
}).describe('Output returned after deleting a Clerk user.')

export const banUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
}).describe('Input for a Clerk user ID.')

export const banUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const unbanUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
}).describe('Input for a Clerk user ID.')

export const unbanUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const lockUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
}).describe('Input for a Clerk user ID.')

export const lockUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

export const unlockUserInput = z.strictObject({
  user_id: z.string().min(1).describe('The Clerk user ID.'),
}).describe('Input for a Clerk user ID.')

export const unlockUserOutput = z.strictObject({
  user: z.looseObject({
    id: z.string().min(1).describe('The Clerk user ID.').optional(),
    object: z.string().describe('The Clerk object type.').optional(),
    username: z.string().describe('The user\'s username when present.').nullable().optional(),
    first_name: z.string().describe('The user\'s first name when present.').nullable().optional(),
    last_name: z.string().describe('The user\'s last name when present.').nullable().optional(),
    image_url: z.string().describe('The user\'s image URL when present.').nullable().optional(),
    has_image: z.boolean().describe('Whether the user has an image.').optional(),
    primary_email_address_id: z.string().describe('The primary email address ID.').nullable().optional(),
    primary_phone_number_id: z.string().describe('The primary phone number ID.').nullable().optional(),
    primary_web3_wallet_id: z.string().describe('The primary Web3 wallet ID.').nullable().optional(),
    password_enabled: z.boolean().describe('Whether password authentication is enabled.').optional(),
    two_factor_enabled: z.boolean().describe('Whether two-factor authentication is enabled.').optional(),
    totp_enabled: z.boolean().describe('Whether TOTP is enabled.').optional(),
    backup_code_enabled: z.boolean().describe('Whether backup codes are enabled.').optional(),
    email_addresses: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Email addresses attached to the user.').optional(),
    phone_numbers: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Phone numbers attached to the user.').optional(),
    web3_wallets: z.array(z.looseObject({
      id: z.string().describe('The identification ID.').optional(),
      object: z.string().describe('The identification object type.').optional(),
      email_address: z.string().describe('The email address value when present.').nullable().optional(),
      phone_number: z.string().describe('The phone number value when present.').nullable().optional(),
      reserved: z.boolean().describe('Whether the identifier is reserved.').optional(),
      verification: z.unknown().describe('The verification state returned by Clerk.').optional(),
      linked_to: z.array(z.unknown().describe('A linked identification reference returned by Clerk.')).describe('External accounts linked to this identification.').optional(),
      created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
      updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    }).describe('A Clerk identification object such as an email address or phone number.')).describe('Web3 wallets attached to the user.').optional(),
    external_accounts: z.array(z.looseObject({
      id: z.string().describe('The external account ID.').optional(),
      object: z.string().describe('The external account object type.').optional(),
      provider: z.string().describe('The external provider identifier.').optional(),
      identification_id: z.string().describe('The related identification ID.').optional(),
      provider_user_id: z.string().describe('The user ID reported by the external provider.').optional(),
      email_address: z.string().describe('The provider email address when present.').nullable().optional(),
      first_name: z.string().describe('The provider first name when present.').nullable().optional(),
      last_name: z.string().describe('The provider last name when present.').nullable().optional(),
      image_url: z.string().describe('The provider image URL when present.').nullable().optional(),
      username: z.string().describe('The provider username when present.').nullable().optional(),
      public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
      verification: z.unknown().describe('The external account verification state returned by Clerk.').optional(),
    }).describe('A Clerk external account attached to the user.')).describe('External accounts attached to the user.').optional(),
    public_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    private_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    unsafe_metadata: z.looseObject({}).describe('Arbitrary Clerk metadata stored on the user.').optional(),
    banned: z.boolean().describe('Whether the user is banned.').optional(),
    locked: z.boolean().describe('Whether the user is locked.').optional(),
    lockout_expires_in_seconds: z.int().describe('Seconds until lockout expires when present.').nullable().optional(),
    verification_attempts_remaining: z.int().describe('Verification attempts remaining when present.').nullable().optional(),
    last_sign_in_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    created_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    updated_at: z.int().describe('Unix timestamp in milliseconds as returned by Clerk.').nullable().optional(),
    delete_self_enabled: z.boolean().describe('Whether the user can delete their own account.').optional(),
    create_organization_enabled: z.boolean().describe('Whether the user can create organizations.').optional(),
    create_organizations_limit: z.int().describe('The organization creation limit when present.').nullable().optional(),
  }).describe('A Clerk user object.'),
}).describe('Output returned with a Clerk user.')

/** action 名 → 注册用的 OperationSpec(description / effect / schema)。 */
export const clerkActions = {
  list_users: {
    description: 'List Clerk users with optional filtering and pagination.',
    effect: 'read',
    inputSchema: listUsersInput,
    outputSchema: z.toJSONSchema(listUsersOutput, { io: 'output', unrepresentable: 'any' }),
  },
  count_users: {
    description: 'Count Clerk users with optional filters.',
    effect: 'read',
    inputSchema: countUsersInput,
    outputSchema: z.toJSONSchema(countUsersOutput, { io: 'output', unrepresentable: 'any' }),
  },
  get_user: {
    description: 'Retrieve a Clerk user by ID.',
    effect: 'read',
    inputSchema: getUserInput,
    outputSchema: z.toJSONSchema(getUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  create_user: {
    description: 'Create a Clerk user.',
    effect: 'write',
    inputSchema: createUserInput,
    outputSchema: z.toJSONSchema(createUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  update_user: {
    description: 'Update a Clerk user.',
    effect: 'write',
    inputSchema: updateUserInput,
    outputSchema: z.toJSONSchema(updateUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  update_user_metadata: {
    description: 'Deep merge metadata for a Clerk user.',
    effect: 'write',
    inputSchema: updateUserMetadataInput,
    outputSchema: z.toJSONSchema(updateUserMetadataOutput, { io: 'output', unrepresentable: 'any' }),
  },
  delete_user: {
    description: 'Delete a Clerk user.',
    effect: 'destructive',
    inputSchema: deleteUserInput,
    outputSchema: z.toJSONSchema(deleteUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  ban_user: {
    description: 'Ban a Clerk user.',
    effect: 'write',
    inputSchema: banUserInput,
    outputSchema: z.toJSONSchema(banUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  unban_user: {
    description: 'Unban a Clerk user.',
    effect: 'write',
    inputSchema: unbanUserInput,
    outputSchema: z.toJSONSchema(unbanUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  lock_user: {
    description: 'Lock a Clerk user.',
    effect: 'write',
    inputSchema: lockUserInput,
    outputSchema: z.toJSONSchema(lockUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
  unlock_user: {
    description: 'Unlock a Clerk user.',
    effect: 'write',
    inputSchema: unlockUserInput,
    outputSchema: z.toJSONSchema(unlockUserOutput, { io: 'output', unrepresentable: 'any' }),
  },
} as const
