/**
 * **此文件由 `scripts/generateRegistry.mjs` 生成,不要手改。**
 * 重新生成:`pnpm --filter @tool-bridge/plugins generate:registry`
 *
 * 内容 = `src/<name>/index.ts` 存在的全部目录。装配逻辑与 env 白名单在手写的
 * `registry.ts` 里 —— 那些是判断,这里只是磁盘事实。
 */

/** 插件模块形状:default export = plugin-sdk 产出的 `{ fetch(request, env) }`。 */
export interface BuiltinPluginModule {
  default: {
    fetch(request: Request, env: never): Promise<Response> | Response
  }
}

/** binding 名 → 懒加载器。"可用 ≠ 实例化":未被调用的插件连模块都不会加载。 */
export const BUILTIN_PLUGIN_LOADERS: Record<string, () => Promise<BuiltinPluginModule>> = {
  airtable: () => import('./airtable/index') as Promise<BuiltinPluginModule>,
  alt_text_generator_ai: () => import('./alt_text_generator_ai/index') as Promise<BuiltinPluginModule>,
  amap: () => import('./amap/index') as Promise<BuiltinPluginModule>,
  anthropic: () => import('./anthropic/index') as Promise<BuiltinPluginModule>,
  apify: () => import('./apify/index') as Promise<BuiltinPluginModule>,
  brave_search: () => import('./brave_search/index') as Promise<BuiltinPluginModule>,
  circleci: () => import('./circleci/index') as Promise<BuiltinPluginModule>,
  clerk: () => import('./clerk/index') as Promise<BuiltinPluginModule>,
  cloudflare_dns: () => import('./cloudflare_dns/index') as Promise<BuiltinPluginModule>,
  cohere: () => import('./cohere/index') as Promise<BuiltinPluginModule>,
  confluence: () => import('./confluence/index') as Promise<BuiltinPluginModule>,
  convertapi: () => import('./convertapi/index') as Promise<BuiltinPluginModule>,
  currencyapi: () => import('./currencyapi/index') as Promise<BuiltinPluginModule>,
  deepseek: () => import('./deepseek/index') as Promise<BuiltinPluginModule>,
  docker_hub: () => import('./docker_hub/index') as Promise<BuiltinPluginModule>,
  dropbox: () => import('./dropbox/index') as Promise<BuiltinPluginModule>,
  dub: () => import('./dub/index') as Promise<BuiltinPluginModule>,
  e2b: () => import('./e2b/index') as Promise<BuiltinPluginModule>,
  exa: () => import('./exa/index') as Promise<BuiltinPluginModule>,
  fal_ai: () => import('./fal_ai/index') as Promise<BuiltinPluginModule>,
  feishu: () => import('./feishu/index') as Promise<BuiltinPluginModule>,
  feishu_custom_bot: () => import('./feishu_custom_bot/index') as Promise<BuiltinPluginModule>,
  figma: () => import('./figma/index') as Promise<BuiltinPluginModule>,
  firehydrant: () => import('./firehydrant/index') as Promise<BuiltinPluginModule>,
  fixer: () => import('./fixer/index') as Promise<BuiltinPluginModule>,
  fly: () => import('./fly/index') as Promise<BuiltinPluginModule>,
  front: () => import('./front/index') as Promise<BuiltinPluginModule>,
  geocodio: () => import('./geocodio/index') as Promise<BuiltinPluginModule>,
  ghost: () => import('./ghost/index') as Promise<BuiltinPluginModule>,
  github: () => import('./github/index') as Promise<BuiltinPluginModule>,
  gmail: () => import('./gmail/index') as Promise<BuiltinPluginModule>,
  googlecalendar: () => import('./googlecalendar/index') as Promise<BuiltinPluginModule>,
  googledocs: () => import('./googledocs/index') as Promise<BuiltinPluginModule>,
  grafana: () => import('./grafana/index') as Promise<BuiltinPluginModule>,
  graphhopper: () => import('./graphhopper/index') as Promise<BuiltinPluginModule>,
  ip2proxy: () => import('./ip2proxy/index') as Promise<BuiltinPluginModule>,
  ipgeolocation_io: () => import('./ipgeolocation_io/index') as Promise<BuiltinPluginModule>,
  ipqualityscore: () => import('./ipqualityscore/index') as Promise<BuiltinPluginModule>,
  jina_ai: () => import('./jina_ai/index') as Promise<BuiltinPluginModule>,
  jira: () => import('./jira/index') as Promise<BuiltinPluginModule>,
  langsmith: () => import('./langsmith/index') as Promise<BuiltinPluginModule>,
  lemlist: () => import('./lemlist/index') as Promise<BuiltinPluginModule>,
  linear: () => import('./linear/index') as Promise<BuiltinPluginModule>,
  logsnag: () => import('./logsnag/index') as Promise<BuiltinPluginModule>,
  mattermost: () => import('./mattermost/index') as Promise<BuiltinPluginModule>,
  mem0: () => import('./mem0/index') as Promise<BuiltinPluginModule>,
  memos: () => import('./memos/index') as Promise<BuiltinPluginModule>,
  metabase: () => import('./metabase/index') as Promise<BuiltinPluginModule>,
  mistral_ai: () => import('./mistral_ai/index') as Promise<BuiltinPluginModule>,
  mother_duck: () => import('./mother_duck/index') as Promise<BuiltinPluginModule>,
  ngrok: () => import('./ngrok/index') as Promise<BuiltinPluginModule>,
  notes: () => import('./notes/index') as Promise<BuiltinPluginModule>,
  notion: () => import('./notion/index') as Promise<BuiltinPluginModule>,
  open_exchange_rates: () => import('./open_exchange_rates/index') as Promise<BuiltinPluginModule>,
  openai: () => import('./openai/index') as Promise<BuiltinPluginModule>,
  opengraph_io: () => import('./opengraph_io/index') as Promise<BuiltinPluginModule>,
  openrouter: () => import('./openrouter/index') as Promise<BuiltinPluginModule>,
  outline: () => import('./outline/index') as Promise<BuiltinPluginModule>,
  paddle: () => import('./paddle/index') as Promise<BuiltinPluginModule>,
  perplexity: () => import('./perplexity/index') as Promise<BuiltinPluginModule>,
  pinecone: () => import('./pinecone/index') as Promise<BuiltinPluginModule>,
  pipedrive: () => import('./pipedrive/index') as Promise<BuiltinPluginModule>,
  polar: () => import('./polar/index') as Promise<BuiltinPluginModule>,
  posthog: () => import('./posthog/index') as Promise<BuiltinPluginModule>,
  postmark: () => import('./postmark/index') as Promise<BuiltinPluginModule>,
  prerender: () => import('./prerender/index') as Promise<BuiltinPluginModule>,
  pubmed: () => import('./pubmed/index') as Promise<BuiltinPluginModule>,
  railway: () => import('./railway/index') as Promise<BuiltinPluginModule>,
  readwise: () => import('./readwise/index') as Promise<BuiltinPluginModule>,
  render: () => import('./render/index') as Promise<BuiltinPluginModule>,
  replicate: () => import('./replicate/index') as Promise<BuiltinPluginModule>,
  resend: () => import('./resend/index') as Promise<BuiltinPluginModule>,
  rootly: () => import('./rootly/index') as Promise<BuiltinPluginModule>,
  scrapfly: () => import('./scrapfly/index') as Promise<BuiltinPluginModule>,
  scrapingbee: () => import('./scrapingbee/index') as Promise<BuiltinPluginModule>,
  screenshot_fyi: () => import('./screenshot_fyi/index') as Promise<BuiltinPluginModule>,
  semantic_scholar: () => import('./semantic_scholar/index') as Promise<BuiltinPluginModule>,
  sentry: () => import('./sentry/index') as Promise<BuiltinPluginModule>,
  shodan: () => import('./shodan/index') as Promise<BuiltinPluginModule>,
  shopify: () => import('./shopify/index') as Promise<BuiltinPluginModule>,
  stripe: () => import('./stripe/index') as Promise<BuiltinPluginModule>,
  supabase: () => import('./supabase/index') as Promise<BuiltinPluginModule>,
  tavily: () => import('./tavily/index') as Promise<BuiltinPluginModule>,
  telegram: () => import('./telegram/index') as Promise<BuiltinPluginModule>,
  telnyx: () => import('./telnyx/index') as Promise<BuiltinPluginModule>,
  todoist: () => import('./todoist/index') as Promise<BuiltinPluginModule>,
  trello: () => import('./trello/index') as Promise<BuiltinPluginModule>,
  turso: () => import('./turso/index') as Promise<BuiltinPluginModule>,
  twilio: () => import('./twilio/index') as Promise<BuiltinPluginModule>,
  umami: () => import('./umami/index') as Promise<BuiltinPluginModule>,
  unsplash: () => import('./unsplash/index') as Promise<BuiltinPluginModule>,
  upstash_redis: () => import('./upstash_redis/index') as Promise<BuiltinPluginModule>,
  uptimerobot: () => import('./uptimerobot/index') as Promise<BuiltinPluginModule>,
  v2ex: () => import('./v2ex/index') as Promise<BuiltinPluginModule>,
  vercel: () => import('./vercel/index') as Promise<BuiltinPluginModule>,
  wolfram_alpha_api: () => import('./wolfram_alpha_api/index') as Promise<BuiltinPluginModule>,
  wordpress: () => import('./wordpress/index') as Promise<BuiltinPluginModule>,
  workos: () => import('./workos/index') as Promise<BuiltinPluginModule>,
  zhihu: () => import('./zhihu/index') as Promise<BuiltinPluginModule>,
}
