/**
 * SatisMeter 各 action 的入参/出参 Zod schema 与语义标注。
 *
 * **由 `scripts/migrate` 从 open-connector 的 action 定义生成**,生成后归本仓库所有:
 * 可以直接改(收紧 schema、改 description、修 effect)。改过的 action 请登记进同目录的
 * `handwritten.json`,否则重新生成会覆盖你的修改,等价闸门也会拿上游 schema 判它。
 *
 * `effect` 上游没有这个轴,生成时按 action 名前缀**播种**(读前缀 read、删除前缀
 * destructive、其余 write),保守取值,以人工校正为准。
 */

import { z } from 'zod/v4'

export const getProjectInput = z.strictObject({
  projectId: z.string().min(1).describe('SatisMeter project ID.').optional(),
}).describe('The input payload for retrieving a SatisMeter project.')

export const getProjectOutput = z.strictObject({
  project: z.looseObject({
    id: z.string().describe('Project ID.').optional(),
    name: z.string().describe('Project name.').optional(),
  }).describe('SatisMeter project.').optional(),
}).describe('The output payload for retrieving a SatisMeter project.')

export const listSurveysInput = z.strictObject({
  projectId: z.string().min(1).describe('SatisMeter project ID.').optional(),
}).describe('The input payload for listing SatisMeter surveys.')

export const listSurveysOutput = z.strictObject({
  surveys: z.array(z.looseObject({
    id: z.string().describe('Survey ID.').optional(),
    name: z.string().describe('Survey name.').optional(),
    type: z.enum(['nps', 'ces', 'csat', 'pmf', 'custom']).describe('Survey template type returned by SatisMeter.').optional(),
    state: z.enum(['live', 'paused', 'draft']).describe('Survey state returned by SatisMeter.').optional(),
  }).describe('SatisMeter survey.')).describe('Surveys returned by SatisMeter.').optional(),
}).describe('The output payload for listing SatisMeter surveys.')

export const getSurveyInput = z.strictObject({
  projectId: z.string().min(1).describe('SatisMeter project ID.').optional(),
  campaignId: z.string().min(1).describe('SatisMeter survey ID.').optional(),
}).describe('The input payload for retrieving a SatisMeter survey.')

export const getSurveyOutput = z.strictObject({
  survey: z.looseObject({
    id: z.string().describe('Survey ID.').optional(),
    name: z.string().describe('Survey name.').optional(),
    type: z.enum(['nps', 'ces', 'csat', 'pmf', 'custom']).describe('Survey template type returned by SatisMeter.').optional(),
    state: z.enum(['live', 'paused', 'draft']).describe('Survey state returned by SatisMeter.').optional(),
  }).describe('SatisMeter survey.').optional(),
}).describe('The output payload for retrieving a SatisMeter survey.')

export const listProjectResponsesInput = z.strictObject({
  projectId: z.string().min(1).describe('SatisMeter project ID.'),
  startDate: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
  endDate: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
  pageCursor: z.string().min(1).describe('Cursor returned by a previous SatisMeter response page.').optional(),
  pageSize: z.int().min(1).max(100).describe('Maximum number of results to return on each page.').optional(),
}).describe('The input payload for listing project-level SatisMeter responses.')

export const listProjectResponsesOutput = z.strictObject({
  responses: z.array(z.looseObject({
    id: z.string().describe('Response ID.').optional(),
    project: z.string().describe('Project ID associated with the response.').optional(),
    campaign: z.string().describe('Survey ID associated with the response.').optional(),
    answers: z.array(z.looseObject({
      id: z.string().describe('Answered question ID.').optional(),
      label: z.string().describe('Question label displayed to the user.').optional(),
      value: z.union([z.string().describe('String answer value.'), z.int().describe('Numeric answer value.'), z.array(z.string().describe('Selected option value.')).describe('Multiple selected values.')]).describe('Answer value returned by SatisMeter.').optional(),
      type: z.enum(['scale', 'smiley', 'long-text', 'single-choice', 'multiple-choice']).describe('Question type returned by SatisMeter.').nullable().optional(),
      metric: z.enum(['nps', 'ces', 'csat', 'pmf']).describe('Metric type returned by SatisMeter.').nullable().optional(),
    }).describe('SatisMeter response answer.')).describe('Answers left in the response.').optional(),
    created: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
    user: z.looseObject({
      id: z.string().describe('Internal user ID assigned by SatisMeter.').optional(),
      deleted: z.boolean().describe('Whether the referenced user has been deleted.').optional(),
      userId: z.string().describe('External user ID stored on the response.').nullable().optional(),
      anonymousId: z.string().describe('Anonymous ID generated by SatisMeter when userId is unavailable.').nullable().optional(),
      traits: z.record(z.string(), z.unknown().describe('A trait value.')).describe('User traits captured when the response was recorded.').optional(),
    }).describe('Responding user returned by SatisMeter.').optional(),
    ip: z.string().describe('IP address of the respondent.').nullable().optional(),
    location: z.looseObject({
      country: z.looseObject({
        code: z.string().describe('ISO 3166 country code.').nullable().optional(),
        name: z.string().describe('Country name.').nullable().optional(),
      }).describe('Country information returned by SatisMeter.').nullable().optional(),
      region: z.looseObject({
        code: z.string().describe('ISO 3166 region code.').nullable().optional(),
        name: z.string().describe('Region name.').nullable().optional(),
      }).describe('Region information returned by SatisMeter.').nullable().optional(),
      city: z.string().describe('City derived from the response IP.').nullable().optional(),
    }).describe('Location information returned by SatisMeter.').optional(),
    referrer: z.string().describe('Page URL where the response was created.').nullable().optional(),
    method: z.enum(['In-app', 'Form', 'Mobile', 'Reminder', 'Email']).describe('Delivery method used for the survey.').optional(),
    language: z.string().describe('ISO 639-1 language code.').nullable().optional(),
    device: z.looseObject({
      type: z.enum(['phone', 'tablet', 'desktop']).describe('Type of the device used by the respondent.').optional(),
      os: z.string().describe('Operating system used by the respondent.').optional(),
    }).describe('Device information returned by SatisMeter.').optional(),
  }).describe('SatisMeter response.')).describe('Responses returned by SatisMeter.').optional(),
  page: z.strictObject({
    nextPageCursor: z.string().describe('Cursor for the next page, or null when there are no more pages.').nullable().optional(),
    hasNextPage: z.boolean().describe('Whether there are more response pages to fetch.').optional(),
    size: z.int().describe('Maximum number of results requested per page.').optional(),
  }).describe('Cursor pagination metadata returned by SatisMeter.').optional(),
}).describe('The output payload for listing project-level SatisMeter responses.')

export const listSurveyResponsesInput = z.strictObject({
  projectId: z.string().min(1).describe('SatisMeter project ID.'),
  startDate: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
  endDate: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
  pageCursor: z.string().min(1).describe('Cursor returned by a previous SatisMeter response page.').optional(),
  pageSize: z.int().min(1).max(100).describe('Maximum number of results to return on each page.').optional(),
  campaignId: z.string().min(1).describe('SatisMeter survey ID.'),
}).describe('The input payload for listing survey-level SatisMeter responses.')

export const listSurveyResponsesOutput = z.strictObject({
  responses: z.array(z.looseObject({
    id: z.string().describe('Response ID.').optional(),
    project: z.string().describe('Project ID associated with the response.').optional(),
    campaign: z.string().describe('Survey ID associated with the response.').optional(),
    answers: z.array(z.looseObject({
      id: z.string().describe('Answered question ID.').optional(),
      label: z.string().describe('Question label displayed to the user.').optional(),
      value: z.union([z.string().describe('String answer value.'), z.int().describe('Numeric answer value.'), z.array(z.string().describe('Selected option value.')).describe('Multiple selected values.')]).describe('Answer value returned by SatisMeter.').optional(),
      type: z.enum(['scale', 'smiley', 'long-text', 'single-choice', 'multiple-choice']).describe('Question type returned by SatisMeter.').nullable().optional(),
      metric: z.enum(['nps', 'ces', 'csat', 'pmf']).describe('Metric type returned by SatisMeter.').nullable().optional(),
    }).describe('SatisMeter response answer.')).describe('Answers left in the response.').optional(),
    created: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
    user: z.looseObject({
      id: z.string().describe('Internal user ID assigned by SatisMeter.').optional(),
      deleted: z.boolean().describe('Whether the referenced user has been deleted.').optional(),
      userId: z.string().describe('External user ID stored on the response.').nullable().optional(),
      anonymousId: z.string().describe('Anonymous ID generated by SatisMeter when userId is unavailable.').nullable().optional(),
      traits: z.record(z.string(), z.unknown().describe('A trait value.')).describe('User traits captured when the response was recorded.').optional(),
    }).describe('Responding user returned by SatisMeter.').optional(),
    ip: z.string().describe('IP address of the respondent.').nullable().optional(),
    location: z.looseObject({
      country: z.looseObject({
        code: z.string().describe('ISO 3166 country code.').nullable().optional(),
        name: z.string().describe('Country name.').nullable().optional(),
      }).describe('Country information returned by SatisMeter.').nullable().optional(),
      region: z.looseObject({
        code: z.string().describe('ISO 3166 region code.').nullable().optional(),
        name: z.string().describe('Region name.').nullable().optional(),
      }).describe('Region information returned by SatisMeter.').nullable().optional(),
      city: z.string().describe('City derived from the response IP.').nullable().optional(),
    }).describe('Location information returned by SatisMeter.').optional(),
    referrer: z.string().describe('Page URL where the response was created.').nullable().optional(),
    method: z.enum(['In-app', 'Form', 'Mobile', 'Reminder', 'Email']).describe('Delivery method used for the survey.').optional(),
    language: z.string().describe('ISO 639-1 language code.').nullable().optional(),
    device: z.looseObject({
      type: z.enum(['phone', 'tablet', 'desktop']).describe('Type of the device used by the respondent.').optional(),
      os: z.string().describe('Operating system used by the respondent.').optional(),
    }).describe('Device information returned by SatisMeter.').optional(),
  }).describe('SatisMeter response.')).describe('Responses returned by SatisMeter.').optional(),
  page: z.strictObject({
    nextPageCursor: z.string().describe('Cursor for the next page, or null when there are no more pages.').nullable().optional(),
    hasNextPage: z.boolean().describe('Whether there are more response pages to fetch.').optional(),
    size: z.int().describe('Maximum number of results requested per page.').optional(),
  }).describe('Cursor pagination metadata returned by SatisMeter.').optional(),
}).describe('The output payload for listing survey-level SatisMeter responses.')

export const getSurveyStatisticsInput = z.strictObject({
  projectId: z.string().min(1).describe('SatisMeter project ID.'),
  campaignId: z.string().min(1).describe('SatisMeter survey ID.'),
  startDate: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
  endDate: z.iso.datetime({ offset: true }).describe('ISO 8601 timestamp with timezone information.').optional(),
}).describe('The input payload for retrieving SatisMeter survey statistics.')

export const getSurveyStatisticsOutput = z.strictObject({
  statistics: z.strictObject({
    statistics: z.strictObject({
      responses: z.int().describe('Total number of responses.').optional(),
      displays: z.int().describe('Total number of survey displays.').optional(),
      responseRate: z.number().describe('Ratio of responses over displays in the selected time range.').optional(),
    }).describe('Top-level survey response statistics.').optional(),
    questions: z.array(z.strictObject({
      id: z.string().describe('Question ID.').optional(),
      label: z.string().describe('Question label in the survey default language.').optional(),
      type: z.enum(['scale', 'smiley', 'long-text', 'single-choice', 'multiple-choice']).describe('Question type returned by SatisMeter.').optional(),
      statistics: z.strictObject({
        answers: z.int().describe('Number of responses that answered this question.').optional(),
        values: z.array(z.strictObject({
          value: z.union([z.string().describe('Possible answer value represented as a string.'), z.int().describe('Possible answer value represented as an integer.')]).describe('Possible answer value.').optional(),
          answers: z.int().describe('Number of answers with this value.').optional(),
        }).describe('Aggregated count for one possible question value.')).describe('Per-value answer counts, or null for long-text questions.').nullable().optional(),
        metric: z.strictObject({
          type: z.enum(['nps', 'ces', 'csat', 'pmf']).describe('Metric type returned by SatisMeter.').optional(),
          value: z.int().describe('Calculated metric value.').optional(),
        }).describe('Metric statistics associated with a question.').nullable().optional(),
      }).describe('Aggregated statistics for the question.').optional(),
    }).describe('Per-question SatisMeter statistics.')).describe('Per-question statistics for the selected survey.').optional(),
  }).describe('Survey statistics returned by SatisMeter.').optional(),
}).describe('The output payload for retrieving SatisMeter survey statistics.')

/** action 名 → 注册用的 OperationSpec(description / effect / schema)。 */
export const satismeterActions = {
  get_project: {
    description: 'Retrieve a SatisMeter project by ID.',
    effect: 'read',
    inputSchema: getProjectInput,
    outputSchema: z.toJSONSchema(getProjectOutput, { io: 'output', unrepresentable: 'any' }),
  },
  list_surveys: {
    description: 'List surveys configured in a SatisMeter project.',
    effect: 'read',
    inputSchema: listSurveysInput,
    outputSchema: z.toJSONSchema(listSurveysOutput, { io: 'output', unrepresentable: 'any' }),
  },
  get_survey: {
    description: 'Retrieve a SatisMeter survey by ID.',
    effect: 'read',
    inputSchema: getSurveyInput,
    outputSchema: z.toJSONSchema(getSurveyOutput, { io: 'output', unrepresentable: 'any' }),
  },
  list_project_responses: {
    description: 'List responses recorded across all surveys in a SatisMeter project.',
    effect: 'read',
    inputSchema: listProjectResponsesInput,
    outputSchema: z.toJSONSchema(listProjectResponsesOutput, { io: 'output', unrepresentable: 'any' }),
  },
  list_survey_responses: {
    description: 'List responses recorded for one SatisMeter survey.',
    effect: 'read',
    inputSchema: listSurveyResponsesInput,
    outputSchema: z.toJSONSchema(listSurveyResponsesOutput, { io: 'output', unrepresentable: 'any' }),
  },
  get_survey_statistics: {
    description: 'Retrieve aggregated statistics for one SatisMeter survey.',
    effect: 'read',
    inputSchema: getSurveyStatisticsInput,
    outputSchema: z.toJSONSchema(getSurveyStatisticsOutput, { io: 'output', unrepresentable: 'any' }),
  },
} as const
