/**
 * PostHog —— 从 open-connector 迁移的 provider(57 个 action:项目、事件/属性定义、
 * 标注、cohort、insight、query、dashboard、feature flag)。
 *
 * 分工同其他迁移产物:`schema.ts` 是生成的 Zod 声明,`api.ts` 是人工改写的业务逻辑,
 * 本文件把两张表对起来(键集合不吻合会在装配期炸)。
 *
 * `credentialProbe: 'get_current_user'` —— 三个条件都满足:已注册、`effect: 'read'`、
 * inputSchema 是 `z.strictObject({})` 没有必填字段。它打的正是上游 `credentialValidators`
 * 用的那个接口(`/api/users/@me/`),挂载时配错的 personal API key 当场被拒。
 *
 * 挂载还需要 `providerConfig.baseUrl`(US/EU/自托管三选一,见 api.ts 顶部)。它不是密钥,
 * 走 providerConfig 通道;探针调用也会带上它,所以 baseUrl 配错同样在挂载期暴露。
 */

import {
  addDashboardCollaborator,
  addPersonsToStaticCohort,
  bulkUpdateEventDefinitionTags,
  bulkUpdatePropertyDefinitionTags,
  cancelQuery,
  copyDashboardTile,
  createAnnotation,
  createCohort,
  createDashboard,
  createEventDefinition,
  createFeatureFlag,
  createInsight,
  deleteAnnotation,
  deleteCohort,
  deleteDashboard,
  deleteEventDefinition,
  deleteFeatureFlag,
  deleteInsight,
  deletePropertyDefinition,
  getAnnotation,
  getAsyncQueryStatus,
  getCohort,
  getCohortCalculationHistory,
  getCohortPersons,
  getCurrentUser,
  getDashboard,
  getEventDefinition,
  getEventDefinitionByName,
  getEventDefinitionPrimaryProperties,
  getFeatureFlag,
  getFeatureFlagDependentFlags,
  getFeatureFlagsLocalEvaluation,
  getFeatureFlagStatus,
  getInsight,
  getProject,
  getPropertyDefinition,
  listAnnotations,
  listCohorts,
  listDashboardCollaborators,
  listDashboards,
  listEventDefinitions,
  listFeatureFlags,
  listInsights,
  listProjects,
  listPropertyDefinitions,
  moveDashboardTile,
  removeDashboardCollaborator,
  reorderDashboardTiles,
  runDashboardInsights,
  runQuery,
  updateAnnotation,
  updateCohort,
  updateDashboard,
  updateEventDefinition,
  updateFeatureFlag,
  updateInsight,
  updatePropertyDefinition,
} from './api'
import { createProviderPlugin, type ProviderEnv } from '../_runtime/plugin'
import { posthogActions } from './schema'

export type { ProviderEnv as Env }

export function createPosthogPlugin(): ReturnType<typeof createProviderPlugin> {
  return createProviderPlugin({
    description: 'PostHog',
    actions: posthogActions,
    credentialProbe: 'get_current_user',
    mountConfigFields: [
      {
        key: 'baseUrl',
        label: 'PostHog API URL',
        description: '例如 https://us.posthog.com、https://eu.posthog.com 或自托管地址',
        required: true,
      },
      {
        key: 'organizationId',
        label: 'Organization ID',
        description: '可选;需要按组织范围调用的接口会使用它',
      },
    ],
    handlers: {
      get_current_user: getCurrentUser,
      list_projects: listProjects,
      get_project: getProject,
      list_event_definitions: listEventDefinitions,
      get_event_definition: getEventDefinition,
      create_event_definition: createEventDefinition,
      update_event_definition: updateEventDefinition,
      delete_event_definition: deleteEventDefinition,
      get_event_definition_by_name: getEventDefinitionByName,
      get_event_definition_primary_properties: getEventDefinitionPrimaryProperties,
      bulk_update_event_definition_tags: bulkUpdateEventDefinitionTags,
      list_property_definitions: listPropertyDefinitions,
      get_property_definition: getPropertyDefinition,
      update_property_definition: updatePropertyDefinition,
      delete_property_definition: deletePropertyDefinition,
      bulk_update_property_definition_tags: bulkUpdatePropertyDefinitionTags,
      list_annotations: listAnnotations,
      get_annotation: getAnnotation,
      create_annotation: createAnnotation,
      update_annotation: updateAnnotation,
      delete_annotation: deleteAnnotation,
      list_cohorts: listCohorts,
      get_cohort: getCohort,
      create_cohort: createCohort,
      update_cohort: updateCohort,
      delete_cohort: deleteCohort,
      add_persons_to_static_cohort: addPersonsToStaticCohort,
      get_cohort_persons: getCohortPersons,
      get_cohort_calculation_history: getCohortCalculationHistory,
      list_insights: listInsights,
      get_insight: getInsight,
      run_query: runQuery,
      get_async_query_status: getAsyncQueryStatus,
      cancel_query: cancelQuery,
      create_insight: createInsight,
      update_insight: updateInsight,
      delete_insight: deleteInsight,
      list_dashboards: listDashboards,
      get_dashboard: getDashboard,
      create_dashboard: createDashboard,
      update_dashboard: updateDashboard,
      delete_dashboard: deleteDashboard,
      run_dashboard_insights: runDashboardInsights,
      copy_dashboard_tile: copyDashboardTile,
      move_dashboard_tile: moveDashboardTile,
      reorder_dashboard_tiles: reorderDashboardTiles,
      list_dashboard_collaborators: listDashboardCollaborators,
      add_dashboard_collaborator: addDashboardCollaborator,
      remove_dashboard_collaborator: removeDashboardCollaborator,
      list_feature_flags: listFeatureFlags,
      get_feature_flag: getFeatureFlag,
      create_feature_flag: createFeatureFlag,
      update_feature_flag: updateFeatureFlag,
      delete_feature_flag: deleteFeatureFlag,
      get_feature_flag_status: getFeatureFlagStatus,
      get_feature_flag_dependent_flags: getFeatureFlagDependentFlags,
      get_feature_flags_local_evaluation: getFeatureFlagsLocalEvaluation,
    },
  })
}

export default createPosthogPlugin()
